apiVersion: v1
kind: Pod
metadata:
  name: dnstools
  labels:
    app: dnstools
spec:
  containers:
  - name: dnstools
    image: nginx:latest
    command:
    - sleep
    - "3600"
  restartPolicy: Always