apiVersion: v1
kind: Pod
metadata:
  name: hellocloud-v1
  labels:
    app: hellocloud
spec:
  containers:
  - name: cnfp1
    image: hashicorp/http-echo
    args:
    - "-listen=:8080"
    - "-text=Welcome to cnfp1-v1"
  - name: cnfp2
    image: hashicorp/http-echo
    args:
    - "-listen=:9090"
    - "-text=Welcome to cnfp2-v1"
  - name: cnfp3
    image: hashicorp/http-echo
    args:
    - "-listen=:7070"
    - "-text=Welcome to cnfp3-v1"

---
apiVersion: v1
kind: Pod
metadata:
  name: hellocloud-v2
  labels:
    app: hellocloud
spec:
  containers:
  - name: cnfp1
    image: hashicorp/http-echo
    args:
    - "-listen=:8080"
    - "-text=Welcome to cnfp1-v2"
  - name: cnfp2
    image: hashicorp/http-echo
    args:
    - "-listen=:9090"
    - "-text=Welcome to cnfp2-v2"
  - name: cnfp3
    image: hashicorp/http-echo
    args:
    - "-listen=:7070"
    - "-text=Welcome to cnfp3-v2"
---
apiVersion: v1
kind: Pod
metadata:
  name: hellocloud-v3
  labels:
    app: hellocloud
spec:
  containers:
  - name: cnfp1
    image: hashicorp/http-echo
    args:
    - "-listen=:8080"
    - "-text=Welcome to cnfp1-v3"
  - name: cnfp2
    image: hashicorp/http-echo
    args:
    - "-listen=:9090"
    - "-text=Welcome to cnfp2-v3"

---
apiVersion: v1
kind: Pod
metadata:
  name: hellocloud-v4
  labels:
    app: hellocloud
spec:
  containers:
  - name: cnfp1
    image: hashicorp/http-echo
    args:
    - "-listen=:8080"
    - "-text=Welcome to cnfp1-v4"
